name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            target: x86_64-linux-gnu
          - os: ubuntu-24.04-arm
            target: aarch64-linux-gnu
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: mlugg/setup-zig@v2.0.5
        with:
          cache-key: test-${{ matrix.target }}
      - run: zig build --summary new -Dtarget=${{ matrix.target }}
      - run: zig build test --summary new -Dtarget=${{ matrix.target }}

  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -fsSL https://raw.githubusercontent.com/DonIsaac/zlint/refs/tags/v0.7.9/tasks/install.sh | bash
      - run: zlint -f github --deny-warnings
      - uses: mlugg/setup-zig@v2.0.5
        with:
          cache-key: lint
      - run: zig build lint
      - run: zig fmt ./ --check
      - name: Detect lines with more than 100 characters
        run: find ./ -type f -name "*.zig" ! -path "./.zig-cache/*" -exec awk 'length($0) > 100 { print; err = 1 } END { exit err }' {} +
